apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: service-registry-group
  namespace: OPERATOR_NAMESPACE
  labels:
    app: service-registry
spec:
  targetNamespaces:
  - OPERATOR_NAMESPACE